apiVersion: v1
kind: Namespace
metadata:
  name: cloudtype
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "${CLOUDFLARE_API_TOKEN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudtype-crt
  namespace: cert-manager
spec:
  acme:
    email: "${CLOUDFLARE_ACME_EMAIL}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudtype-crt
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          cloudflare:
            email: "${CLOUDFLARE_ACME_EMAIL}"
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsZones:
            - [Cloudflare에 등록된 도메인]
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudtype-tls
  namespace: cloudtype
spec:
  dnsNames:
    - "[Cloudflare에 등록된 도메인]"
    - "*.[Cloudflare에 등록된 도메인]"
  issuerRef:
    kind: ClusterIssuer
    name: cloudtype-crt
  secretName: cloudtype-tls